"""initial schema

Revision ID: aa7522716f77
Revises: 
Create Date: 2026-07-22 18:41:37.906459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa7522716f77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=32), nullable=True),
    sa.Column('utility_types', sa.ARRAY(sa.Enum('ELECTRICITY', 'GAS', 'WATER', 'SEWAGE', 'DISTRICT_HEATING', 'WASTE', name='utility_type')), nullable=False),
    sa.Column('parser_key', sa.String(length=64), nullable=False),
    sa.Column('detection_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=32), nullable=True),
    sa.Column('subscription_plan', sa.Enum('TRIAL', 'STANDARD', 'PRO', 'ENTERPRISE', name='subscription_plan'), nullable=False),
    sa.Column('subscription_status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='subscription_status'), nullable=False),
    sa.Column('gcs_prefix', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumption_points',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('utility_type', sa.Enum('ELECTRICITY', 'GAS', 'WATER', 'SEWAGE', 'DISTRICT_HEATING', 'WASTE', name='utility_type'), nullable=False),
    sa.Column('pod', sa.String(length=64), nullable=True),
    sa.Column('poc', sa.String(length=64), nullable=True),
    sa.Column('heating_center_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consumption_points_tenant_pod', 'consumption_points', ['tenant_id', 'pod'], unique=False)
    op.create_index('ix_consumption_points_tenant_utility', 'consumption_points', ['tenant_id', 'utility_type'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('partner_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_consumption_point_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('gcs_path', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'DONE', 'FAILED', 'NEEDS_REVIEW', name='document_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_documents_tenant_hash')
    )
    op.create_table('meters',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('consumption_point_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('meter_type', sa.Enum('ELECTRICITY', 'GAS', 'WATER', 'HEAT', name='meter_type'), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consumption_point_id'], ['consumption_points.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meters_tenant_serial', 'meters', ['tenant_id', 'serial_number'], unique=False)
    op.create_table('invoices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('consumption_point_id', sa.UUID(), nullable=True),
    sa.Column('utility_type', sa.Enum('ELECTRICITY', 'GAS', 'WATER', 'SEWAGE', 'DISTRICT_HEATING', 'WASTE', name='utility_type'), nullable=False),
    sa.Column('invoice_type', sa.Enum('COMMERCIAL', 'NETWORK_USAGE_FEE', 'CAPACITY_FEE', 'PARTIAL', 'SETTLEMENT', 'STORNO', 'CORRECTION', name='invoice_type'), nullable=False),
    sa.Column('delivery_format', sa.Enum('ELECTRONIC', 'SCANNED_PAPER', name='delivery_format'), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('performance_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('billing_period_start', sa.Date(), nullable=True),
    sa.Column('billing_period_end', sa.Date(), nullable=True),
    sa.Column('pod', sa.String(length=64), nullable=True),
    sa.Column('poc', sa.String(length=64), nullable=True),
    sa.Column('metering_point', sa.String(length=64), nullable=True),
    sa.Column('heating_center_id', sa.String(length=64), nullable=True),
    sa.Column('meter_serial_number', sa.String(length=128), nullable=True),
    sa.Column('contract_number', sa.String(length=128), nullable=True),
    sa.Column('current_account_number', sa.String(length=128), nullable=True),
    sa.Column('partner_code', sa.String(length=64), nullable=True),
    sa.Column('customer_reference', sa.String(length=128), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('meter_reading_start', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('meter_reading_end', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('consumption_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('consumption_unit', sa.String(length=16), nullable=True),
    sa.Column('reactive_energy_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('contracted_capacity_kw', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('measured_max_capacity_kw', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALID', 'INVALID', 'NEEDS_REVIEW', name='validation_status'), nullable=False),
    sa.Column('processing_status', sa.Enum('QUEUED', 'PROCESSING', 'DONE', 'FAILED', 'NEEDS_REVIEW', name='processing_status'), nullable=False),
    sa.Column('raw_ai_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['consumption_point_id'], ['consumption_points.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index('ix_invoices_tenant_number', 'invoices', ['tenant_id', 'invoice_number'], unique=False)
    op.create_index('ix_invoices_tenant_period', 'invoices', ['tenant_id', 'billing_period_start', 'billing_period_end'], unique=False)
    op.create_index('ix_invoices_tenant_pod', 'invoices', ['tenant_id', 'pod'], unique=False)
    op.create_index('ix_invoices_tenant_provider', 'invoices', ['tenant_id', 'provider_id'], unique=False)
    op.create_index('ix_invoices_tenant_utility_type', 'invoices', ['tenant_id', 'utility_type', 'invoice_type'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('unit_net_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vat_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_line_items_tenant_invoice', 'invoice_line_items', ['tenant_id', 'invoice_id'], unique=False)
    op.create_table('meter_readings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('meter_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('reading_date', sa.Date(), nullable=False),
    sa.Column('reading_type', sa.Enum('START', 'END', name='reading_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reading_method', sa.Enum('ACTUAL', 'ESTIMATED', name='reading_method'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_runs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('TEXT_EXTRACTION', 'OCR', 'DOC_TYPE_CLASSIFICATION', 'PROVIDER_CLASSIFICATION', 'INVOICE_TYPE_CLASSIFICATION', 'PARSING', 'AI_STRUCTURING', 'VALIDATION', 'REPROCESSING', name='pipeline_stage'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='run_status'), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_issues',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('processing_run_id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'ERROR', name='issue_severity'), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_issues')
    op.drop_table('processing_runs')
    op.drop_table('meter_readings')
    op.drop_index('ix_invoice_line_items_tenant_invoice', table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_invoices_tenant_utility_type', table_name='invoices')
    op.drop_index('ix_invoices_tenant_provider', table_name='invoices')
    op.drop_index('ix_invoices_tenant_pod', table_name='invoices')
    op.drop_index('ix_invoices_tenant_period', table_name='invoices')
    op.drop_index('ix_invoices_tenant_number', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_meters_tenant_serial', table_name='meters')
    op.drop_table('meters')
    op.drop_table('documents')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('ix_consumption_points_tenant_utility', table_name='consumption_points')
    op.drop_index('ix_consumption_points_tenant_pod', table_name='consumption_points')
    op.drop_table('consumption_points')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('providers')
    op.drop_table('partners')
    # ### end Alembic commands ###

    # SQLAlchemy/Alembic does not auto-drop shared PostgreSQL ENUM types on
    # drop_table, since multiple tables/columns can reference the same type.
    for enum_name in [
        "utility_type",
        "invoice_type",
        "delivery_format",
        "document_status",
        "processing_status",
        "validation_status",
        "subscription_plan",
        "subscription_status",
        "meter_type",
        "reading_type",
        "reading_method",
        "pipeline_stage",
        "run_status",
        "issue_severity",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    op.execute("DROP EXTENSION IF EXISTS citext")
