"""invoice sites and secondary utility types

Revision ID: b47f7ec3488e
Revises: 1b56ede9ea9f
Create Date: 2026-07-23 07:35:17.425224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b47f7ec3488e'
down_revision: Union[str, None] = '1b56ede9ea9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Same RLS policy shape as 99eedb16dff3 — see that migration's docstring for
# why NULLIF(..., '') is required instead of a plain NULL check.
POLICY_USING_CLAUSE = (
    "tenant_id = NULLIF(current_setting('app.current_tenant_id', true), '')::uuid "
    "OR NULLIF(current_setting('app.current_tenant_id', true), '') IS NULL"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sites',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('consumption_point_id', sa.UUID(), nullable=True),
    sa.Column('site_address', sa.String(length=500), nullable=False),
    sa.Column('site_identifier', sa.String(length=64), nullable=True),
    sa.Column('meter_serial_number', sa.String(length=128), nullable=True),
    sa.Column('consumption_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('consumption_unit', sa.String(length=16), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consumption_point_id'], ['consumption_points.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_sites_tenant_invoice', 'invoice_sites', ['tenant_id', 'invoice_id'], unique=False)
    op.add_column(
        'invoices',
        sa.Column(
            'secondary_utility_types',
            sa.ARRAY(sa.Enum('ELECTRICITY', 'GAS', 'WATER', 'SEWAGE', 'DISTRICT_HEATING', 'WASTE', name='utility_type')),
            nullable=False,
            server_default='{}',
        ),
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE invoice_sites ENABLE ROW LEVEL SECURITY")
    op.execute(f"CREATE POLICY tenant_isolation_invoice_sites ON invoice_sites USING ({POLICY_USING_CLAUSE})")


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation_invoice_sites ON invoice_sites")
    op.execute("ALTER TABLE invoice_sites DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'secondary_utility_types')
    op.drop_index('ix_invoice_sites_tenant_invoice', table_name='invoice_sites')
    op.drop_table('invoice_sites')
    # ### end Alembic commands ###
